### ISSUE TITLE
Compile error in v0.10.0 (also in v9.3 branch)

### ISSUE THREAD

**Issue by nomaxpi** [IXCoin-Dev/IXCoin#11]
I'm getting this when I try to compile on gnu/linux gcc v4.8.2 Ubuntu 12.05 and 14.04

  CXX    rpcmining.o
  CXX    rpcmisc.o
  CXX    rpcnet.o
rpcnet.cpp: In function ‘json_spirit::Value sendalert(const Array&, bool)’:
rpcnet.cpp:485:56: error: ‘FALSE’ was not declared in this scope
rpcnet.cpp:493:79: error: ‘FALSE’ was not declared in this scope
make[3]: *** [rpcnet.o] Error 1
make[3]: Leaving directory `/root/IXCoin/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/IXCoin/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/root/IXCoin/src'
make: *** [all-recursive] Error 1

I think the compiler see's "FALSE" versus "false" as a type error. I tested it and changing them to lowercase resolved the compiler issue. I can submit a PR if needed.

Thanks

**Comment by GroundRod** [comment]
Please do submit a PR for fixing it.  Remember now originally using upper case on TRUE/FALSE early on when starting to work on the code, thought I had fixed all of them, but obviously missed a few, now hopefully you've caught the rest....  

Wondering why my Debian g++ 4.7.2-5 compiler isn't reported it as an error also.  Back when those were introduced, I was still building via mingw32 on a windows xp-sp3 32 bit os.

Good catch, and thanks for reporting it...

GR

**Comment by nomaxpi** [comment]
Closing per merge https://github.com/IXCoin-Dev/IXCoin/commit/a5fa583c9361c16354f777eb3f36942d54659eb5
